trigger:
- main   # or master, adjust based on your branch

pool:
  name: Default   # this matches the agent pool where your Mac agent will be registered
  demands:
  - agent.os -equals Darwin   # ensures the job runs only on macOS agents

steps:
- script: echo "✅ Running on self-hosted Mac agent"
  displayName: "Verify agent connection"

# Example: Python setup (since SafePipe uses Python)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: "Set up Python"

- script: |
    python --version
    pip install -r requirements.txt
    python scanner.py
  displayName: "Run SafePipe Scanner"
